### ISSUE TITLE
Add adnotation about the current Optimism mainnet launch safeguards

### ISSUE THREAD

**Issue by luke7211** [krzkaczor/l2beat#35]
- no way to use Fraud Proof verifier making this effectively PoA sidechain rather than proper rollup
- enqueuing transactions via L1 currently disabled
- deployment on L2 only whitelisted smart contracts (currently only Synthetix)

**Comment by krzkaczor** [comment]
> no way to use Fraud Proof verifier making this effectively PoA sidechain rather than proper rollup

This claim seems to be correct. Resolver resolves "OVM_FraudVerifier" to https://etherscan.io/address/0xDDB4ae08438057FCfA323b20910f79912723a550 which is EoA. This prevents anyone to submit fraud proofs. This is quite bad.

> enqueuing transactions via L1 currently disabled

Are you sure about it? As far as I can see it's enabled and working - enqueuing **a single tx** via L1 aka. force a single tx mechanism: https://github.com/ethereum-optimism/contracts/blob/master/contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol#L256 it's deployed here: https://etherscan.io/address/0xed2701f7135eab0d7ca02e6ab634ad6cbe159ffb

What is disabled is `appendQueueBatch` which makes optimism permissoned. This prevents anyone from submitting their own tx **batch**. This is already noted in https://github.com/krzkaczor/l2beat/blob/master/frontend/data/projects-data.json#L22

> deployment on L2 only whitelisted smart contracts (currently only Synthetix)

This is already noted in https://github.com/krzkaczor/l2beat/blob/master/frontend/data/projects-data.json#L38

Probably the presentation of this could be better. 

CC: @ben-chain, @smartcontracts
