### ISSUE TITLE
Add zkSwap

### ISSUE THREAD

**Issue by krzkaczor** [krzkaczor/l2beat#47]
Original PR was merged here: https://github.com/krzkaczor/l2beat/pull/32 and later reverted.

We can't add it to l2beat unless the code is verified on etherscan. Once it's don't we are happy to add it.

**Comment by krzkaczor** [comment]
CC: @ZKSwap-fe

**Comment by ZKSwap-fe** [comment]
Hi,

The contract has been verified on etherscan. You can check it here: https://etherscan.io/address/0x2F70F6D864F8F597a0ef57aDDf24323DFAb5797f#code.

Can you go ahead for adding ZKSwap?
