### ISSUE TITLE
Add Layer2.Finance Rollup

### ISSUE THREAD

**Issue by luke7211** [krzkaczor/l2beat#58]
https://blog.celer.network/2021/04/22/the-layer2-finance-v0-1-mainnet-launches-democratize-defi-simple-and-zero-fees/

**Comment by luke7211** [comment]
Deposit Contract: 0xf86fd6735f88d5b6aa709b357ad5be22cedf1a05, accepting USDT, DAI, WETH, USDC, BUSD

**Comment by krzkaczor** [comment]
Rel: https://github.com/krzkaczor/l2beat/pull/59

**Comment by krzkaczor** [comment]
Closed via https://github.com/krzkaczor/l2beat/pull/61
